#List of blocks that are allowed to be covered. Supports '*' as a wildcard.
blocks = ["fluxnetworks:flux_point", "fluxnetworks:flux_plug", "xnet:connector_*", "xnet:advanced_connector_*", "xnet:netcable_*", "integrateddynamics:cable", "ftbic:*_cable", "refinedstorage:constructor", "refinedstorage:destructor", "refinedstorage:importer", "refinedstorage:external_storage", "refinedstorage:exporter", "ae2:*_bus", "ae2:*_cable", "refinedstorage:cable", "pipez:*_pipe", "mekanism:*_cable", "mekanism:*_conductor", "mekanism:*_pipe", "mekanism:*_tube", "mekanism:*_transporter", "mekanism_extras:*_cable", "mekanism_extras:*_conductor", "mekanism_extras:*_pipe", "mekanism_extras:*_tube", "mekanism_extras:*_transporter", "thermal:*_duct", "thermal:*_duct_windowed", "computercraft:cable", "powah:energy_cable_*", "create:fluid_pipe", "pneumaticcraft:*_tube", "laserio:laser_*", "cyclic:*_pipe", "embers:*_pipe", "elementalcraft:elementpipe*", "gtceu:*wire", "gtceu:*pipe", "ae2:cable_bus"]
#List of blocks that are explicitly not allowed to be used as a cover. Supports '*' as a wildcard.
not_allowed_blocks = []
#Whether the facade should be consumed when placed.
consumeFacade = true
#Config version. Increment to apply changes.
#Range: > 1
configVersion = 1
#List of additional blocks added in this version.
added_blocks = []
#List of blocks from the previous version. Do not modify manually.
last_version_blocks = []
#Previous config version. Do not modify manually.
#Range: > 0
lastConfigVersion = 1

