ServerEvents.recipes(event => {
    const { custommachinery } = event.recipes

    custommachinery.custom_machine("minecraft:resource_converter", 35)
        .requireEnergy(2000)
        .requireItem('minecraft:zombie_spawn_egg').chance(0)
        .produceItem('8x oreberriesreplanted:iron_oreberry')
        .produceItem('4x oreberriesreplanted:iron_oreberry').chance(0.5)
        .produceItem('4x oreberriesreplanted:iron_oreberry').chance(0.25)
        .produceItem('2x oreberriesreplanted:iron_oreberry').chance(0.75)
        .produceItem('2x oreberriesreplanted:iron_oreberry').chance(0.5)

    custommachinery.custom_machine("minecraft:resource_converter", 35)
        .requireEnergy(2000)
        .requireItem('minecraft:witch_spawn_egg').chance(0)
        .requireItem('minecraft:spider_spawn_egg').chance(0)
        .requireItem('minecraft:skeleton_spawn_egg').chance(0)
        .requireItem('minecraft:creeper_spawn_egg').chance(0)
        .produceItem('4x ae2:matter_ball')
        .produceItem('3x ae2:matter_ball').chance(0.5)
        .produceItem('3x ae2:matter_ball').chance(0.25)
        .produceItem('2x ae2:matter_ball').chance(0.75)
        .produceItem('2x ae2:matter_ball').chance(0.5)

    custommachinery.custom_machine("minecraft:resource_converter", 100)
        .requireEnergy(20000)
        .requireItem('oritech:uranium_pellet')
        .produceItem('powah:uraninite_ore_poor')
        .produceItem('powah:uraninite_ore_poor').chance(0.5)
        .produceItem('powah:uraninite_ore').chance(0.3)
        .produceItem('powah:uraninite_ore_dense').chance(0.15)
        .produceItem('powah:uraninite_ore_dense').chance(0.05)
        .produceItem('oritech:uranium_crystal').chance(0.25)

    custommachinery.custom_machine("minecraft:resource_converter", 20)
        .requireEnergyPerTick(256)
        .requireItem('4x ae2:matter_ball')
        .produceItem('minecraft:ender_pearl')
        .produceItem('minecraft:ender_pearl').chance(0.5)
        .produceItem('minecraft:ender_pearl').chance(0.3)
        .produceItem('minecraft:ender_pearl').chance(0.25)
        .produceItem('minecraft:ender_pearl').chance(0.2)
        .produceItem('minecraft:ender_pearl').chance(0.15)
        .produceItem('minecraft:ender_pearl').chance(0.1)

    custommachinery.custom_machine("minecraft:resource_converter", 35)
        .requireEnergy(20000)
        .requireItem('4x silentgear:emerald_shard')
        .requireItem('actuallyadditions:enori_crystal')
        .requireItem('mysticalagriculture:dye_essence')
        .produceItem('minecraft:emerald')
        .produceItem('minecraft:emerald').chance(0.5)
        .produceItem('minecraft:emerald').chance(0.25)

    custommachinery.custom_machine("minecraft:resource_converter", 100)
        .requireEnergyPerTick(8192)
        .requireItem('ars_nouveau:wilden_tribute')
        .requireItem('8x alltheores:platinum_ingot')
        .requireItem('64x mysticalagriculture:dye_essence')
        .requireItem('64x ars_nouveau:source_gem')
        .produceItem('2x ars_nouveau:wilden_tribute')
        .produceItem('ars_nouveau:wilden_tribute').chance(0.25)

    custommachinery.custom_machine("minecraft:resource_converter", 100)
        .requireEnergyPerTick(2000)
        .requireItem('minecraft:skeleton_spawn_egg').chance(0)
        .requireItem('hostilenetworks:prediction_matrix').chance(0.25)
        .produceItem('4x mysticalagriculture:skeleton_essence')
        .produceItem('2x mysticalagriculture:skeleton_essence').chance(0.5)
        .produceItem('mysticalagriculture:skeleton_essence').chance(0.5)

    custommachinery.custom_machine("minecraft:resource_converter", 100)
        .requireEnergyPerTick(8000)
        .requireItem('hostilenetworks:prediction_matrix')
        .requireItem('4x minecraft:soul_sand')
        .requireItem('3x minecraft:wither_skeleton_skull')
        .produceItem('minecraft:nether_star')
        .produceItem('minecraft:nether_star').chance(0.25)
    custommachinery.custom_machine("minecraft:resource_converter", 40)
        .requireEnergyPerTick(4096)
        .requireItem('16x minecraft:redstone')
        .produceItem('16x fluxnetworks:flux_dust')
        .produceItem('16x fluxnetworks:flux_dust').chance(0.25)
        .produceItem('8x fluxnetworks:flux_dust').chance(0.5)
})