#Energy per operation in Joules of: Recycler
# Default: 50
# Range: 0 ~ 9223372036854775807
recycler = 50
#Energy per operation in Joules of: Planting Station
# Default: 50
# Range: 0 ~ 9223372036854775807
plantingStation = 50
#Energy per operation in Joules of: CNC Stamper
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_stamper = 50
#Energy per operation in Joules of: CNC Lathe
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_lathe = 50
#Energy per operation in Joules of: CNC Rolling Mill
# Default: 50
# Range: 0 ~ 9223372036854775807
cnc_rollingMill = 50
#Energy per operation in Joules of: Replicator
# Default: 102400
# Range: 0 ~ 9223372036854775807
replicator = 102400
#Energy per operation in Joules of: Ambient Gas Collector
# Default: 100
# Range: 0 ~ 9223372036854775807
ambientGasCollector = 100
