#Options that affect the added Wooden Hopper.
["Wooden Hopper Settings"]
	#Time (ticks) that passes between two wooden hopper operations. (default: 16 ticks) (vanilla hopper: 8 ticks)
	# Default: 16
	# Range: 1 ~ 1000
	woodenHopperCooldown = 16
	#Whether the wooden hopper can pull item entities lying above it. (default: true)
	woodenHopperPullItemsFromWorldEnabled = true
	#Whether the wooden hopper can pull items from inventories above it. (default: true)
	woodenHopperPullItemsFromInventoriesEnabled = true
