name: 上传到七牛存储
on: push

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: windows-latest
    steps:
    - name: 检索文件
      uses: actions/checkout@v2

    - name: Setup CMake
      run: |
        echo $env:GITHUB_RUN_NUMBER