name: 上传到七牛存储
on: push

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          pip install requests

      - name: Set file permissions
        run: |
          dir

      - name: 运行脚本
        run: |
          python mc.py id=$env:GITHUB_RUN_NUMBER url='https://mmc.miniskins.top'
