name: 上传到七牛存储
on: push

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Setup OpenSSL
        run: |
          $PSVersionTable
          Install-Module -Name 7Zip4Powershell
          dir