name: 上传到七牛存储
on: push

jobs:
  build-windows:
    name: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Setup OpenSSL
        run: |
          pwd
          echo "1111111111111"
          ssh-add - <<< "${{ secrets.GITEE_RSA }}"
          echo "2222222222222"
          git config --global user.name "123456"
          git config --global user.email "123456@qq.com"
          mkdir cs
          cd cs
          git init
          touch README.md
          git add .
          git commit -m "first commit"
          git remote add origin git@gitee.com:15874613/cs.git
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push -u origin "master" || exit 1


