name: 上传到七牛存储
on: push

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: windows-latest
    steps:
    - name: 检索文件
      uses: actions/checkout@v2

    - name: Setup CMake
      run: |
        curl -L https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-windows-i386.zip -o cmake.zip
        unzip cmake.zip
        zip -9 -r 1.zip ./
        dir