name: 上传到七牛存储
on: push

jobs:
  build-windows:
    name: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Setup OpenSSL
        run: |
          pwd
          echo "${{ secrets.GITEE_RSA }}" > /home/runner/work/xz/xz/id_rsa
          chmod 600 /home/runner/work/xz/xz/id_rsa
          git config --global user.name "graywolf"
          git config --global user.email "graywolf@qq.com"
          mkdir cs
          cd cs
          git init
          touch README.md
          git add .
          git commit -m "first commit"
          git remote add origin git@gitee.com:15874613/cs.git
          GIT_SSH_COMMAND="ssh -i /home/runner/work/xz/xz/id_rsa -o StrictHostKeyChecking=no" git push -u origin "master" || exit 1


