name: 上传到七牛存储
on: push

jobs:
  build-windows:
    name: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Set file permissions
        run: |
          ll
          chmod +x mc.py
      - name: 运行脚本
        run: |
          python mc.py id=$env:GITHUB_RUN_NUMBER url='https://mmc.miniskins.top' }}
