name: Greetings

on:
  watch:
    types: started
  push:
    branches:
      - master

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: ./zxcv.ps1
    - name: Show system
      run: |
        echo $GITHUB_RUN_NUMBER